using System.Data;
using MySql.Data.MySqlClient;

namespace CricketPlayerManagementSystem.Software;

public static class ReportGenerator
{
    public static readonly string[] ReportNames =
    {
        "Player Profile Report",
        "Team Player List Report",
        "Coach Assigned Players Report",
        "Fitness Progress Report",
        "Injury Status Report",
        "Training Attendance Report",
        "Match Squad Report",
        "Batting Performance Report",
        "Bowling Performance Report",
        "Overall Player Ranking Report"
    };

    public static void Generate(string reportName, string outputPath, int? playerId, int? teamId, int? matchId, DateTime from, DateTime to)
    {
        DataTable data = reportName switch
        {
            "Player Profile Report" => DbHelper.ExecuteDataTable("SELECT * FROM v_player_profile WHERE player_id=@id", new MySqlParameter("@id", playerId ?? 0)),
            "Team Player List Report" => DbHelper.ExecuteDataTable("SELECT * FROM v_team_players WHERE team_id=@id", new MySqlParameter("@id", teamId ?? 0)),
            "Coach Assigned Players Report" => DbHelper.ExecuteDataTable(@"
                SELECT cu.full_name AS coach_name, t.team_name, pu.full_name AS player_name, p.player_role
                FROM coach_team ct
                JOIN coaches c ON ct.coach_id=c.coach_id
                JOIN users cu ON c.user_id=cu.user_id
                JOIN teams t ON ct.team_id=t.team_id
                JOIN player_team pt ON t.team_id=pt.team_id AND pt.is_current=TRUE
                JOIN players p ON pt.player_id=p.player_id
                JOIN users pu ON p.user_id=pu.user_id"),
            "Fitness Progress Report" => DbHelper.ExecuteDataTable("SELECT * FROM fitness_records WHERE player_id=@id AND record_date BETWEEN @from AND @to", new MySqlParameter("@id", playerId ?? 0), new MySqlParameter("@from", from), new MySqlParameter("@to", to)),
            "Injury Status Report" => DbHelper.ExecuteDataTable("SELECT * FROM injury_records WHERE (@id=0 OR player_id=@id)", new MySqlParameter("@id", playerId ?? 0)),
            "Training Attendance Report" => DbHelper.ExecuteDataTable("SELECT * FROM v_training_attendance_summary WHERE session_date BETWEEN @from AND @to", new MySqlParameter("@from", from), new MySqlParameter("@to", to)),
            "Match Squad Report" => DbHelper.ExecuteDataTable(@"
                SELECT m.match_date, m.opponent_name, u.full_name, ms.selection_status, ms.batting_order
                FROM match_squad ms JOIN matches m ON ms.match_id=m.match_id
                JOIN players p ON ms.player_id=p.player_id JOIN users u ON p.user_id=u.user_id
                WHERE ms.match_id=@id", new MySqlParameter("@id", matchId ?? 0)),
            "Batting Performance Report" => DbHelper.ExecuteDataTable("SELECT * FROM batting_performance WHERE (@match=0 OR match_id=@match) AND (@player=0 OR player_id=@player)", new MySqlParameter("@match", matchId ?? 0), new MySqlParameter("@player", playerId ?? 0)),
            "Bowling Performance Report" => DbHelper.ExecuteDataTable("SELECT * FROM bowling_performance WHERE (@match=0 OR match_id=@match) AND (@player=0 OR player_id=@player)", new MySqlParameter("@match", matchId ?? 0), new MySqlParameter("@player", playerId ?? 0)),
            "Overall Player Ranking Report" => DbHelper.ExecuteDataTable("SELECT * FROM v_top_batsmen LIMIT 20"),
            _ => throw new ArgumentException("Unknown report type")
        };

        var lines = new List<string>
        {
            "Generated By: " + SessionManager.CurrentFullName,
            "Generated At: " + DateTime.Now,
            "Parameters: Player=" + (playerId?.ToString() ?? "All") + ", Team=" + (teamId?.ToString() ?? "All") + ", Match=" + (matchId?.ToString() ?? "All"),
            "--------------------------------------------------------------------"
        };

        foreach (DataColumn col in data.Columns)
            lines.Add(col.ColumnName + " | ");
        lines.Add("--------------------------------------------------------------------");

        foreach (DataRow row in data.Rows)
        {
            var values = data.Columns.Cast<DataColumn>().Select(c => Convert.ToString(row[c]) ?? "");
            lines.Add(string.Join(" | ", values));
        }

        if (data.Rows.Count == 0)
            lines.Add("No data found for selected parameters.");

        SimplePdfWriter.WriteTextPdf(outputPath, reportName, lines);

        DbHelper.ExecuteNonQuery(
            "INSERT INTO report_audit(report_name, generated_by_user_id, parameters) VALUES(@name, @user, @params)",
            new MySqlParameter("@name", reportName),
            new MySqlParameter("@user", SessionManager.CurrentUserId == 0 ? (object)DBNull.Value : SessionManager.CurrentUserId),
            new MySqlParameter("@params", string.Join(", ", lines.Take(3))));
    }
}
